steps:
- name: "gcr.io/cloud-builders/docker"
  args: [ 'build', '-t', 'australia-southeast1-docker.pkg.dev/s222527602/drashti-docker-repo/drashti-image:taglatest', '.' ]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetesdeploy.yaml
  - --location=australia-southeast1
  - --cluster=drashti
images:
- 'australia-southeast1-docker.pkg.dev/s222527602/drashti-docker-repo/drashti-image:taglatest'
options:
  logging: CLOUD_LOGGING_ONLY